name       : valadoc
version    : 0.36.0
release    : 2
source     :
    - https://download.gnome.org/sources/valadoc/0.36/valadoc-0.36.0.tar.xz : f564ad83ee195d1b4ff1430efad45bde209156e0ad5660bf6d1045f204766789
license    : GPL-2.0
component  : programming.tools
summary    : A documentation tool for vala
description: |
    Valadoc is a documentation generator for generating API documentation from Vala source code based on libvala.
builddeps  :
    - vala
    - pkgconfig(libvala-0.36)
    - pkgconfig(libgvc)
    - pkgconfig(gee-0.8)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
